name: Java CI with Maven and MySQL Setup

on:
  push:
    branches:
      - "main"
      - "lwj_user_auth"
      - "whq"
      - "yxr"
      - "zry"
  pull_request:
    branches:
      - "main"
      - "lwj_user_auth"
      - "whq"
      - "yxr"
      - "zry"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 检出代码

      # 设置 JDK 8 环境
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      # 关闭默认的 MySQL 服务
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop

      # 设置 MySQL 实例
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql root password: '123456'
          mysql database: 'my_db'


      # 等待 MySQL 启动
      - name: Wait for MySQL to start
        run: sleep 1

      # 检查 MySQL 服务是否启动成功
      - name: Check MySQL service status
        run: mysqladmin -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD ping
        env:
          MYSQL_ROOT_PASSWORD: '123456'

      # 执行 SQL 文件
      - name: Execute SQL file
        run: mysql -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD my_db < ${{ github.workspace }}/sql/create_table.sql
        env:
          MYSQL_ROOT_PASSWORD: '123456'

      # 使用 Maven 构建项目
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 可选：提交 Maven 依赖图
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6