name: Java CI with Maven and MySQL Setup

on:
  push:
    branches:
      - "main"
      - "lwj_user_auth"
      - "whq"
      - "yxr"
      - "zry"
  pull_request:
    branches:
      - "main"
      - "lwj_user_auth"
      - "whq"
      - "yxr"
      - "zry"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 设置 JDK 8 环境
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      # 设置 MySQL 实例
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql root password: '123456'
          mysql database: 'my_db'

      # 设置 MYSQL_PWD 环境变量
      - name: Set MYSQL_PWD environment variable
        run: echo "MYSQL_PWD=$MYSQL_ROOT_PASSWORD" >> $GITHUB_ENV
        env:
          MYSQL_ROOT_PASSWORD: '123456'

      # 等待 MySQL 启动
      - name: Wait for MySQL to start
        run: sleep 2

      # 执行 SQL 文件
      - name: Execute SQL file
        run: mysql -h 127.0.0.1 -u root my_db < ${{ github.workspace }}/sql/create_tables.sql

      # 使用 Maven 构建项目
      - name: Build with Maven
        run: mvn -B package --file pom.xml