name: Java CI with Maven, MySQL Setup, and Snyk Check

on:
  push:
    branches:
      - "main"
      - "CICD-PIPELINE"
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # 检出代码

      # 关闭默认的 MySQL 服务（如果存在）
      - name: Shutdown system MySQL service (if running)
        run: sudo service mysql stop

      # 设置 JDK 8 环境
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      # 设置 MySQL 实例，确保端口映射正确
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql root password: '123456'    # 使用提供的 MySQL root 密码
          mysql database: 'letcode'
          host port: 3306                  # 映射主机端口
          container port: 3306             # 容器内的 MySQL 端口

      # 增加等待时间，确保 MySQL 启动
      - name: Wait for MySQL to start
        run: sleep 10

      # 设置 MYSQL_PWD 环境变量，避免命令行传递密码
      - name: Set MYSQL_PWD environment variable
        run: echo "MYSQL_PWD=$MYSQL_ROOT_PASSWORD" >> $GITHUB_ENV
        env:
          MYSQL_ROOT_PASSWORD: '123456'    # 使用提供的 MySQL root 密码

      # 检查 MySQL 服务状态
      - name: Check MySQL service status
        run: mysqladmin -h 127.0.0.1 -u root ping

      # 执行 SQL 文件
      - name: Execute SQL file
        run: mysql -h 127.0.0.1 -u root letcode < ${{ github.workspace }}/sql/create_table.sql

      # 确保 Maven Wrapper 有执行权限
      - name: Add execution permissions for Maven wrapper
        run: chmod +x ./mvnw

      # 使用 Maven 构建项目
      - name: Build with Maven
        run: ./mvnw -B package --file pom.xml

      # 使用 Snyk 检查依赖漏洞
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true  # 即使 Snyk 检查失败，仍继续执行后续步骤
        with:
          args: test  # 指定 Snyk 运行命令
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # 从 GitHub Secrets 中获取 Snyk API Token