name: SpotBugs Check
on:
  push:
    branches:
      - "main"
      - "lwj_user_auth"
      - "whq"
      - "yxr"
      - "zry"
      - "CICD-PIPELINE"
  pull_request:
    branches:
      - "main"
      - "lwj_user_auth"
      - "whq"
      - "yxr"
      - "zry"
      - "CICD-PIPELINE"

jobs:
  spotbugs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs